#!/usr/bin/env python3
"""Fail closed when the generated IFC catalog collapses back into one monolith."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "packages/openbim.ifc"
FACADE = PACKAGE / "Catalog.pkl"
INTERNAL = PACKAGE / "internal"
EXPECTED = (
    INTERNAL / "Names.pkl",
    INTERNAL / "Ifc2x3Data.pkl",
    INTERNAL / "Ifc4Data.pkl",
    INTERNAL / "Ifc4x3Data.pkl",
    INTERNAL / "Transitions.pkl",
)


def fail(message: str) -> None:
    print(f"IFC catalog modularity check failed: {message}", file=sys.stderr)
    raise SystemExit(1)


def main() -> int:
    missing = [path.relative_to(PACKAGE).as_posix() for path in EXPECTED if not path.is_file()]
    if missing:
        fail(f"missing generated internal modules: {', '.join(missing)}")

    facade = FACADE.read_text(encoding="utf-8")
    facade_lines = facade.count("\n") + (not facade.endswith("\n"))
    if facade_lines > 250:
        fail(f"Catalog.pkl has {facade_lines} lines; expected at most 250")
    if "new ifc.DirectEntityDefinition {" in facade:
        fail("Catalog.pkl contains physical declaration data")

    for path in EXPECTED:
        text = path.read_text(encoding="utf-8")
        if not text.startswith("// Code generated by scripts/render-ifc-catalogs.py; DO NOT EDIT.\n"):
            fail(f"{path.relative_to(PACKAGE)} lacks the generated-file marker")

    print(
        "IFC catalog modularity: "
        f"facade={facade_lines} lines internal_modules={len(EXPECTED)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
