#!/usr/bin/env python3
"""Fail closed when generated IFC catalogs collapse or expose internal storage."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "packages/openbim.ifc"
INTERNAL = PACKAGE / "internal"
ENTITY_INTERNAL = tuple(INTERNAL / name for name in (
    "Names.pkl", "Ifc2x3Data.pkl", "Ifc4Data.pkl", "Ifc4x3Data.pkl", "Transitions.pkl",
))
TEMPLATE_INTERNAL = tuple(INTERNAL / name for name in (
    "TemplateNames.pkl", "TemplateIfc2x3Data.pkl", "TemplateIfc4Data.pkl",
    "TemplateIfc4x3Data.pkl", "TemplateTransitions.pkl",
))


def fail(message: str) -> None:
    print(f"IFC catalog modularity check failed: {message}", file=sys.stderr)
    raise SystemExit(1)


def check_facade(name: str, physical_marker: str, maximum_lines: int) -> int:
    path = PACKAGE / name
    text = path.read_text(encoding="utf-8")
    lines = text.count("\n") + (not text.endswith("\n"))
    if lines > maximum_lines:
        fail(f"{name} has {lines} lines; expected at most {maximum_lines}")
    if physical_marker in text:
        fail(f"{name} contains physical declaration data")
    return lines


def main() -> int:
    expected = ENTITY_INTERNAL + TEMPLATE_INTERNAL
    missing = [path.relative_to(PACKAGE).as_posix() for path in expected if not path.is_file()]
    if missing:
        fail(f"missing generated internal modules: {', '.join(missing)}")
    entity_lines = check_facade("Catalog.pkl", "new ifc.DirectEntityDefinition {", 250)
    template_lines = check_facade(
        "TemplateCatalog.pkl", "new ifc.DirectTemplateSetDefinition {", 350,
    )
    markers = (
        (ENTITY_INTERNAL, "// Code generated by scripts/render-ifc-catalogs.py; DO NOT EDIT.\n"),
        (TEMPLATE_INTERNAL, "// Code generated by scripts/render-ifc-template-catalogs.py; DO NOT EDIT.\n"),
    )
    for paths, marker in markers:
        for path in paths:
            if not path.read_text(encoding="utf-8").startswith(marker):
                fail(f"{path.relative_to(PACKAGE)} lacks the correct generated-file marker")
    for wrapper in (PACKAGE / "versions").glob("*.pkl"):
        text = wrapper.read_text(encoding="utf-8")
        if "TemplateCatalog.pkl" in text:
            fail(f"{wrapper.relative_to(PACKAGE)} makes template parsing non-optional")
        if 'import "../internal/' in text:
            fail(f"{wrapper.relative_to(PACKAGE)} imports unsupported internals")
    for wrapper in (PACKAGE / "templates").glob("*.pkl"):
        text = wrapper.read_text(encoding="utf-8")
        if 'import "../TemplateCatalog.pkl" as catalog' not in text:
            fail(f"{wrapper.relative_to(PACKAGE)} does not use the public template facade")
        if 'import "../internal/' in text:
            fail(f"{wrapper.relative_to(PACKAGE)} imports unsupported internals")
    print(
        "IFC catalog modularity: "
        f"entity_facade={entity_lines} template_facade={template_lines} "
        f"internal_modules={len(expected)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
