"""Split the deterministic IFC catalog render into cohesive Pkl modules."""

from __future__ import annotations

from pathlib import Path

GENERATED_MARKER = "// Code generated by scripts/render-ifc-catalogs.py; DO NOT EDIT."


def _module(name: str, body: str, *, imports: str = "") -> str:
    imports_block = f"\n{imports.strip()}\n" if imports else ""
    return f"{GENERATED_MARKER}\nmodule openbim.ifc.internal.{name}\n{imports_block}\n{body.strip()}\n"


def modularize(monolith: str) -> dict[Path, str]:
    """Return package-relative generated paths without changing public members."""
    names_marker = "/// Closed union across all supported snapshots; resolver availability remains release-bound."
    counts_marker = "revisionCount: UInt = "
    baseline_marker = "/// IFC2X3 is the physical baseline; entries are immediate parent plus directly declared slots."
    ifc4_marker = "/// IFC4 only stores additions and changed direct declarations relative to IFC2X3."
    ifc4x3_marker = "/// IFC4X3 only stores additions and changed direct declarations relative to IFC4."
    transitions_marker = "/// Observed supported-snapshot transitions only; these make no normative lifecycle claim."
    api_marker = "/// Normative lifecycle evidence is intentionally empty until a sourced changelog exporter supplies it."

    markers = (
        names_marker,
        counts_marker,
        baseline_marker,
        ifc4_marker,
        ifc4x3_marker,
        transitions_marker,
        api_marker,
    )
    positions = [monolith.find(marker) for marker in markers]
    if any(position < 0 for position in positions) or positions != sorted(positions):
        raise ValueError("generated IFC catalog semantic markers are missing or reordered")

    header = monolith[: positions[0]]
    names = monolith[positions[0] : positions[1]]
    counts = monolith[positions[1] : positions[2]]
    baseline = monolith[positions[2] : positions[3]]
    ifc4 = monolith[positions[3] : positions[4]]
    ifc4x3 = monolith[positions[4] : positions[5]]
    transitions = monolith[positions[5] : positions[6]]
    api = monolith[positions[6] :]

    facade_imports = '''import "./ifc.pkl" as ifc
import "./internal/Names.pkl" as names
import "./internal/Ifc2x3Data.pkl" as ifc2x3
import "./internal/Ifc4Data.pkl" as ifc4
import "./internal/Ifc4x3Data.pkl" as ifc4x3
import "./internal/Transitions.pkl" as transitions'''
    header = header.replace('import "./ifc.pkl" as ifc', facade_imports, 1)
    if header == monolith[: positions[0]]:
        raise ValueError("generated IFC catalog facade import anchor is missing")

    aliases = f'''typealias EntityName = names.EntityName

entityNames: List<EntityName> = names.entityNames
{counts.strip()}

ifc2x3Baseline: Mapping<String, ifc.DirectEntityDefinition> = ifc2x3.ifc2x3Baseline
ifc4Delta: Mapping<String, ifc.DirectEntityDefinition> = ifc4.ifc4Delta
ifc4Removed: List<String> = ifc4.ifc4Removed
ifc4x3Delta: Mapping<String, ifc.DirectEntityDefinition> = ifc4x3.ifc4x3Delta
ifc4x3Removed: List<String> = ifc4x3.ifc4x3Removed
ifc4ObservedAdded: List<String> = transitions.ifc4ObservedAdded
ifc4ObservedRemoved: List<String> = transitions.ifc4ObservedRemoved
ifc4x3ObservedAdded: List<String> = transitions.ifc4x3ObservedAdded
ifc4x3ObservedRemoved: List<String> = transitions.ifc4x3ObservedRemoved
'''
    facade = f"{header.rstrip()}\n\n{aliases}\n{api.lstrip()}"

    return {
        Path("Catalog.pkl"): facade,
        Path("internal/Names.pkl"): _module("Names", names),
        Path("internal/Ifc2x3Data.pkl"): _module(
            "Ifc2x3Data", baseline, imports='import "../ifc.pkl" as ifc'
        ),
        Path("internal/Ifc4Data.pkl"): _module(
            "Ifc4Data", ifc4, imports='import "../ifc.pkl" as ifc'
        ),
        Path("internal/Ifc4x3Data.pkl"): _module(
            "Ifc4x3Data", ifc4x3, imports='import "../ifc.pkl" as ifc'
        ),
        Path("internal/Transitions.pkl"): _module("Transitions", transitions),
    }


def write_modules(monolith: str, output_dir: Path) -> tuple[Path, ...]:
    written: list[Path] = []
    for relative, content in modularize(monolith).items():
        destination = output_dir / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content, encoding="utf-8")
        written.append(destination)
    return tuple(written)
