#!/usr/bin/env python3
"""Render official release-explicit IFC PSD/QTO reference catalogs from TSV exports."""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
from dataclasses import dataclass
from pathlib import Path

GENERATED = "// Code generated by scripts/render-ifc-template-catalogs.py; DO NOT EDIT."
SOURCE_COMMIT = "f378f824a3787a11218466a8c63ecd0984d0240b"


@dataclass(frozen=True)
class Edition:
    file_name: str
    module_name: str
    release_id: str
    property_sets: int
    quantity_sets: int
    members: int
    rows: int
    tsv_sha256: str
    source_digest: str


EDITIONS = (
    Edition("ifc2x3-tc1.tsv", "Ifc2x3", "IFC2X3_TC1", 317, 0, 1856, 3019,
            "6950f7686b67b68d456e2dde0be9fcae83cbc7849171a1d2c9bf95d4b0718586",
            "395dcd1e8c6f8e5feeece08e8b46e211a3c35a7fc13a7a237485ea48b3c93d53"),
    Edition("ifc4-add2-tc1.tsv", "Ifc4", "IFC4_ADD2_TC1", 420, 93, 2807, 3525,
            "15dca1204b3f7533b2ee85fe353ad1d9b23fdf318fcb46100bef45dd5c2eb42c",
            "57227d4c82f9903bc59cb5bade18a49f2c5f2c9363d0293ccb68fed8765d36e3"),
    Edition("ifc4x3-add2.tsv", "Ifc4x3", "IFC4X3_ADD2", 502, 110, 3242, 4361,
            "11fb5c50dd87b78ccc3f5c09470942cc5d454760d07054d9b879fafe26a737c1",
            "b2f327638a844c8666d38dff90c5a48e12fdcec73da9efc4789e2dedd9239298"),
)
HEADER = (
    "edition", "source_digest", "set_kind", "set_name", "set_guid",
    "set_template_type", "applicable_entity", "predefined_type",
    "includes_subtypes", "member_path", "member_guid", "member_kind",
    "value_type", "unit_type", "source_path", "source_file_digest",
)


@dataclass(frozen=True, order=True)
class Applicability:
    entity: str
    predefined_type: str | None
    includes_subtypes: bool


@dataclass(frozen=True)
class Member:
    source_guid: str | None
    kind: str
    value_type: str
    unit_type: str | None


@dataclass(frozen=True)
class Definition:
    kind: str
    source_guid: str | None
    template_type: str
    applicability: tuple[Applicability, ...]
    members: tuple[tuple[str, Member], ...]


@dataclass(frozen=True)
class Provenance:
    path: str
    sha256: str


def optional(value: str) -> str | None:
    return value or None


def quoted(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def nullable(value: str | None) -> str:
    return "null" if value is None else quoted(value)


def pkl_list(values: list[str] | tuple[str, ...]) -> str:
    return "List()" if not values else "List(" + ", ".join(quoted(value) for value in values) + ")"


def read_edition(path: Path, edition: Edition) -> tuple[dict[str, Definition], dict[str, Provenance]]:
    raw = path.read_bytes()
    actual_digest = hashlib.sha256(raw).hexdigest()
    if actual_digest != edition.tsv_sha256:
        raise ValueError(f"{path}: SHA-256 {actual_digest} != {edition.tsv_sha256}")
    rows = []
    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader((line for line in handle if line.strip()), delimiter="\t")
        if tuple(reader.fieldnames or ()) != HEADER:
            raise ValueError(f"{path}: unexpected TSV header")
        rows = list(reader)
    if len(rows) != edition.rows:
        raise ValueError(f"{path}: row count {len(rows)} != {edition.rows}")

    mutable: dict[str, dict[str, object]] = {}
    for row in rows:
        if row["edition"] != edition.release_id or row["source_digest"] != edition.source_digest:
            raise ValueError(f"{path}: release/source digest drift")
        name = row["set_name"]
        current = mutable.setdefault(name, {
            "kind": row["set_kind"], "guid": optional(row["set_guid"]),
            "template_type": row["set_template_type"], "applicability": set(),
            "members": {}, "source": Provenance(row["source_path"], row["source_file_digest"]),
        })
        stable = (current["kind"], current["guid"], current["template_type"], current["source"])
        observed = (row["set_kind"], optional(row["set_guid"]), row["set_template_type"],
                    Provenance(row["source_path"], row["source_file_digest"]))
        if stable != observed:
            raise ValueError(f"{path}: inconsistent set row for {name}")
        current["applicability"].add(Applicability(
            row["applicable_entity"], optional(row["predefined_type"]),
            row["includes_subtypes"] == "true",
        ))
        member = Member(optional(row["member_guid"]), row["member_kind"],
                        row["value_type"], optional(row["unit_type"]))
        previous = current["members"].setdefault(row["member_path"], member)
        if previous != member:
            raise ValueError(f"{path}: inconsistent member {name}.{row['member_path']}")

    definitions: dict[str, Definition] = {}
    provenance: dict[str, Provenance] = {}
    for name, current in sorted(mutable.items()):
        definitions[name] = Definition(
            str(current["kind"]), current["guid"], str(current["template_type"]),
            tuple(sorted(current["applicability"])), tuple(sorted(current["members"].items())),
        )
        provenance[name] = current["source"]
    property_sets = sum(value.kind == "psd" for value in definitions.values())
    quantity_sets = sum(value.kind == "qto" for value in definitions.values())
    members = sum(len(value.members) for value in definitions.values())
    actual = (property_sets, quantity_sets, members)
    expected = (edition.property_sets, edition.quantity_sets, edition.members)
    if actual != expected:
        raise ValueError(f"{path}: inventory {actual} != {expected}")
    return definitions, provenance


def render_definition(value: Definition, indent: str = "  ") -> str:
    applicability = "List()" if not value.applicability else "List(\n" + "\n".join(
        f"{indent}  new ifc.TemplateApplicability {{ entity = {quoted(item.entity)}; "
        f"predefinedType = {nullable(item.predefined_type)}; includesSubtypes = {str(item.includes_subtypes).lower()} }},"
        for item in value.applicability
    ) + f"\n{indent})"
    members = "new {\n" + "\n".join(
        f"{indent}  [{quoted(path)}] = new ifc.DirectTemplateMemberDefinition {{\n"
        f"{indent}    sourceGuid = {nullable(member.source_guid)}\n"
        f"{indent}    kind = {quoted(member.kind)}\n"
        f"{indent}    valueType = {quoted(member.value_type)}\n"
        f"{indent}    unitType = {nullable(member.unit_type)}\n"
        f"{indent}  }}"
        for path, member in value.members
    ) + f"\n{indent}}}"
    return (
        "new ifc.DirectTemplateSetDefinition {\n"
        f"{indent}kind = {quoted(value.kind)}\n"
        f"{indent}sourceGuid = {nullable(value.source_guid)}\n"
        f"{indent}templateType = {quoted(value.template_type)}\n"
        f"{indent}applicability = {applicability}\n"
        f"{indent}members = {members}\n"
        f"{indent[:-2]}}}"
    )


def render_definitions(name: str, values: dict[str, Definition]) -> str:
    body = "\n".join(
        f"  [{quoted(key)}] = {render_definition(value, '    ')}"
        for key, value in sorted(values.items())
    )
    return f"{name}: Mapping<String, ifc.DirectTemplateSetDefinition> = new {{\n{body}\n}}\n"


def render_provenance(name: str, values: dict[str, Provenance]) -> str:
    body = "\n".join(
        f"  [{quoted(key)}] = new ifc.TemplateSourceProvenance {{ path = {quoted(value.path)}; sha256 = {quoted(value.sha256)} }}"
        for key, value in sorted(values.items())
    )
    return f"{name}: Mapping<String, ifc.TemplateSourceProvenance> = new {{\n{body}\n}}\n"


def render_union(name: str, values: list[str]) -> str:
    return f"typealias {name} =\n  " + "\n    | ".join(quoted(value) for value in values) + "\n"


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def module(name: str, body: str, imports: str = "") -> str:
    block = f"\n{imports}\n" if imports else ""
    return f"{GENERATED}\nmodule openbim.ifc.internal.{name}\n{block}\n{body}"


def render_facade(
    catalogs: list[dict[str, Definition]], provenance: list[dict[str, Provenance]],
    deltas: list[dict[str, Definition]], removed: list[list[str]],
    added: list[list[str]], changed: list[list[str]], package_version: str,
) -> str:
    releases = []
    release_props = ("ifc2x3Release", "ifc4Release", "ifc4x3Release")
    data_aliases = ("ifc2x3", "ifc4", "ifc4x3")
    for edition, prop in zip(EDITIONS, release_props, strict=True):
        releases.append(f'''{edition.module_name[0].lower() + edition.module_name[1:]}TemplateCatalog: ifc.TemplateCatalogRelease = new ifc.TemplateCatalogRelease {{
  release = catalog.{prop}
  sourceUri = "https://github.com/openbimrs/ifc/blob/{SOURCE_COMMIT}/ifc-template-catalog/data/{edition.file_name}"
  sourceSha256 = "{edition.tsv_sha256}"
  sourceDigest = "{edition.source_digest}"
  exporterCommit = "{SOURCE_COMMIT}"
  setCount = {edition.property_sets + edition.quantity_sets}
  propertySetCount = {edition.property_sets}
  quantitySetCount = {edition.quantity_sets}
  memberCount = {edition.members}
  rowCount = {edition.rows}
}}''')
    return f'''{GENERATED}
/// Official release-explicit PSD/QTO reference catalog.
/// Source `openbimrs/ifc` commit: {SOURCE_COMMIT}
module openbim.ifc.TemplateCatalog

import "./ifc.pkl" as ifc
import "./Catalog.pkl" as catalog
import "./internal/TemplateNames.pkl" as names
import "./internal/TemplateIfc2x3Data.pkl" as ifc2x3
import "./internal/TemplateIfc4Data.pkl" as ifc4
import "./internal/TemplateIfc4x3Data.pkl" as ifc4x3
import "./internal/TemplateTransitions.pkl" as transitions

typealias TemplateSetName = names.TemplateSetName
typealias PropertySetName = names.PropertySetName
typealias QuantitySetName = names.QuantitySetName
typealias TemplateMemberPath = names.TemplateMemberPath

templateSetNames: List<TemplateSetName> = names.templateSetNames
propertySetNames: List<PropertySetName> = names.propertySetNames
quantitySetNames: List<QuantitySetName> = names.quantitySetNames
templateMemberPaths: List<TemplateMemberPath> = names.templateMemberPaths

{chr(10).join(releases)}

function templateCatalogFor(release: ifc.ReleaseId): ifc.TemplateCatalogRelease =
  if (release == "IFC2X3_TC1") ifc2x3TemplateCatalog
  else if (release == "IFC4_ADD2_TC1") ifc4TemplateCatalog
  else ifc4x3TemplateCatalog

function hasTemplateSet(release: ifc.ReleaseId, name: String): Boolean =
  if (release == "IFC2X3_TC1") ifc2x3.definitions.containsKey(name)
  else if (release == "IFC4_ADD2_TC1")
    !ifc4.removed.contains(name) && (ifc4.delta.containsKey(name) || ifc2x3.definitions.containsKey(name))
  else
    !ifc4x3.removed.contains(name) && (ifc4x3.delta.containsKey(name) || hasTemplateSet("IFC4_ADD2_TC1", name))

function templateSetNamesFor(release: ifc.ReleaseId): List<TemplateSetName> =
  templateSetNames.filter((name) -> hasTemplateSet(release, name))
function propertySetNamesFor(release: ifc.ReleaseId): List<PropertySetName> =
  propertySetNames.filter((name) -> hasTemplateSet(release, name) && directDefinition(release, name).kind == "psd")
function quantitySetNamesFor(release: ifc.ReleaseId): List<QuantitySetName> =
  quantitySetNames.filter((name) -> hasTemplateSet(release, name) && directDefinition(release, name).kind == "qto")

function directDefinition(release: ifc.ReleaseId, name: String): ifc.DirectTemplateSetDefinition =
  if (!hasTemplateSet(release, name)) throw("template set is absent from \\(release): \\(name)")
  else if (release == "IFC2X3_TC1") ifc2x3.definitions[name]
  else if (release == "IFC4_ADD2_TC1")
    if (ifc4.delta.containsKey(name)) ifc4.delta[name] else ifc2x3.definitions[name]
  else if (ifc4x3.delta.containsKey(name)) ifc4x3.delta[name]
  else directDefinition("IFC4_ADD2_TC1", name)

function sourceFor(release: ifc.ReleaseId, name: String): ifc.TemplateSourceProvenance =
  if (release == "IFC2X3_TC1") ifc2x3.sources[name]
  else if (release == "IFC4_ADD2_TC1") ifc4.sources[name]
  else ifc4x3.sources[name]

function templateSet(release_: ifc.ReleaseId, name_: String): ifc.TemplateSetReference =
  let (definition = directDefinition(release_, name_))
    new ifc.TemplateSetReference {{
      release = release_
      externalTypeSystem = catalog.releaseFor(release_).externalTypeSystem
      packageCatalogUri = "package://openbimrs.github.io/pkl/openbim.ifc@{package_version}#/templates/\\(release_)/\\(definition.kind)/\\(name_)"
      kind = definition.kind
      name = name_
      sourceGuid = definition.sourceGuid
      templateType = definition.templateType
      applicability = definition.applicability
      members = definition.members
      source = sourceFor(release_, name_)
    }}

function propertySet(release_: ifc.ReleaseId, name_: String): ifc.TemplateSetReference =
  let (reference = templateSet(release_, name_))
    if (reference.kind == "psd") reference else throw("not a property set in \\(release_): \\(name_)")

function quantitySet(release_: ifc.ReleaseId, name_: String): ifc.TemplateSetReference =
  let (reference = templateSet(release_, name_))
    if (reference.kind == "qto") reference else throw("not a quantity set in \\(release_): \\(name_)")

function member(release_: ifc.ReleaseId, setName_: String, path_: String): ifc.TemplateMemberReference =
  let (setReference = templateSet(release_, setName_))
    if (!setReference.members.containsKey(path_))
      throw("template member is absent from \\(release_): \\(setName_).\\(path_)")
    else let (definition = setReference.members[path_])
      new ifc.TemplateMemberReference {{
        templateSet = setReference
        release = release_
        externalTypeSystem = setReference.externalTypeSystem
        packageCatalogUri = "\\(setReference.packageCatalogUri)/\\(path_)"
        path = path_
        sourceGuid = definition.sourceGuid
        kind = definition.kind
        valueType = definition.valueType
        unitType = definition.unitType
      }}

function property(release_: ifc.ReleaseId, setName_: String, path_: String): ifc.TemplateMemberReference =
  let (_ = propertySet(release_, setName_)) member(release_, setName_, path_)

function quantity(release_: ifc.ReleaseId, setName_: String, path_: String): ifc.TemplateMemberReference =
  let (_ = quantitySet(release_, setName_)) member(release_, setName_, path_)

function definitionsFor(name: String): Mapping<ifc.ReleaseId, ifc.DirectTemplateSetDefinition> = new {{
  when (hasTemplateSet("IFC2X3_TC1", name)) {{ ["IFC2X3_TC1"] = directDefinition("IFC2X3_TC1", name) }}
  when (hasTemplateSet("IFC4_ADD2_TC1", name)) {{ ["IFC4_ADD2_TC1"] = directDefinition("IFC4_ADD2_TC1", name) }}
  when (hasTemplateSet("IFC4X3_ADD2", name)) {{ ["IFC4X3_ADD2"] = directDefinition("IFC4X3_ADD2", name) }}
}}

normativeTemplateContinuityEvidence: List<ifc.TemplateContinuityEvidence> = List()

function setEvolution(name_: TemplateSetName): ifc.TemplateSetEvolution = setEvolutionByName(name_)
function setEvolutionByName(name_: String): ifc.TemplateSetEvolution =
  if (!hasTemplateSet("IFC2X3_TC1", name_) && !hasTemplateSet("IFC4_ADD2_TC1", name_) && !hasTemplateSet("IFC4X3_ADD2", name_))
    throw("unknown IFC template set: \\(name_)")
  else new ifc.TemplateSetEvolution {{
    name = name_
    definitions = definitionsFor(name_)
    observedAddedIn =
      (if (transitions.ifc4Added.contains(name_)) List("IFC4_ADD2_TC1") else List())
        + (if (transitions.ifc4x3Added.contains(name_)) List("IFC4X3_ADD2") else List())
    observedRemovedIn =
      (if (transitions.ifc4Removed.contains(name_)) List("IFC4_ADD2_TC1") else List())
        + (if (transitions.ifc4x3Removed.contains(name_)) List("IFC4X3_ADD2") else List())
    observedChangedIn =
      (if (transitions.ifc4Changed.contains(name_)) List("IFC4_ADD2_TC1") else List())
        + (if (transitions.ifc4x3Changed.contains(name_)) List("IFC4X3_ADD2") else List())
    continuityEvidence = normativeTemplateContinuityEvidence.filter((it) -> it.setName == name_ && it.memberPath == null)
  }}

function hasMember(release: ifc.ReleaseId, setName: String, path: String): Boolean =
  hasTemplateSet(release, setName) && directDefinition(release, setName).members.containsKey(path)

function directMemberDefinition(release: ifc.ReleaseId, setName: String, path: String): ifc.DirectTemplateMemberDefinition =
  if (!hasMember(release, setName, path))
    throw("template member is absent from \\(release): \\(setName).\\(path)")
  else directDefinition(release, setName).members[path]

function memberDefinitionsFor(setName: String, path: String): Mapping<ifc.ReleaseId, ifc.DirectTemplateMemberDefinition> = new {{
  when (hasMember("IFC2X3_TC1", setName, path)) {{ ["IFC2X3_TC1"] = directMemberDefinition("IFC2X3_TC1", setName, path) }}
  when (hasMember("IFC4_ADD2_TC1", setName, path)) {{ ["IFC4_ADD2_TC1"] = directMemberDefinition("IFC4_ADD2_TC1", setName, path) }}
  when (hasMember("IFC4X3_ADD2", setName, path)) {{ ["IFC4X3_ADD2"] = directMemberDefinition("IFC4X3_ADD2", setName, path) }}
}}

function memberEvolution(setName_: TemplateSetName, path_: TemplateMemberPath): ifc.TemplateMemberEvolution =
  memberEvolutionByName(setName_, path_)
function memberEvolutionByName(setName_: String, path_: String): ifc.TemplateMemberEvolution =
  if (!hasMember("IFC2X3_TC1", setName_, path_) && !hasMember("IFC4_ADD2_TC1", setName_, path_) && !hasMember("IFC4X3_ADD2", setName_, path_))
    throw("unknown IFC template member: \\(setName_).\\(path_)")
  else new ifc.TemplateMemberEvolution {{
    setName = setName_
    path = path_
    definitions = memberDefinitionsFor(setName_, path_)
    observedAddedIn =
      (if (!hasMember("IFC2X3_TC1", setName_, path_) && hasMember("IFC4_ADD2_TC1", setName_, path_)) List("IFC4_ADD2_TC1") else List())
        + (if (!hasMember("IFC4_ADD2_TC1", setName_, path_) && hasMember("IFC4X3_ADD2", setName_, path_)) List("IFC4X3_ADD2") else List())
    observedRemovedIn =
      (if (hasMember("IFC2X3_TC1", setName_, path_) && !hasMember("IFC4_ADD2_TC1", setName_, path_)) List("IFC4_ADD2_TC1") else List())
        + (if (hasMember("IFC4_ADD2_TC1", setName_, path_) && !hasMember("IFC4X3_ADD2", setName_, path_)) List("IFC4X3_ADD2") else List())
    observedChangedIn =
      (if (hasMember("IFC2X3_TC1", setName_, path_) && hasMember("IFC4_ADD2_TC1", setName_, path_)
        && directMemberDefinition("IFC2X3_TC1", setName_, path_) != directMemberDefinition("IFC4_ADD2_TC1", setName_, path_)) List("IFC4_ADD2_TC1") else List())
        + (if (hasMember("IFC4_ADD2_TC1", setName_, path_) && hasMember("IFC4X3_ADD2", setName_, path_)
          && directMemberDefinition("IFC4_ADD2_TC1", setName_, path_) != directMemberDefinition("IFC4X3_ADD2", setName_, path_)) List("IFC4X3_ADD2") else List())
    continuityEvidence = normativeTemplateContinuityEvidence.filter((it) -> it.setName == setName_ && it.memberPath == path_)
  }}
'''


def render_version_view(edition: Edition) -> str:
    return f'''{GENERATED}
/// Official {edition.release_id} PSD/QTO reference view.
module openbim.ifc.templates.{edition.module_name}

import "../ifc.pkl" as ifc
import "../TemplateCatalog.pkl" as catalog

release: ifc.Release = catalog.templateCatalogFor("{edition.release_id}").release
templateCatalog: ifc.TemplateCatalogRelease = catalog.templateCatalogFor(release.id)
typealias TemplateSetName = catalog.TemplateSetName
typealias PropertySetName = catalog.PropertySetName
typealias QuantitySetName = catalog.QuantitySetName
typealias TemplateMemberPath = catalog.TemplateMemberPath

templateSetNames: List<TemplateSetName> = catalog.templateSetNamesFor(release.id)
propertySetNames: List<PropertySetName> = catalog.propertySetNamesFor(release.id)
quantitySetNames: List<QuantitySetName> = catalog.quantitySetNamesFor(release.id)

function templateSet(name_: TemplateSetName): ifc.TemplateSetReference = catalog.templateSet(release.id, name_)
function templateSetByName(name_: String): ifc.TemplateSetReference = catalog.templateSet(release.id, name_)
function propertySet(name_: PropertySetName): ifc.TemplateSetReference = catalog.propertySet(release.id, name_)
function propertySetByName(name_: String): ifc.TemplateSetReference = catalog.propertySet(release.id, name_)
function quantitySet(name_: QuantitySetName): ifc.TemplateSetReference = catalog.quantitySet(release.id, name_)
function quantitySetByName(name_: String): ifc.TemplateSetReference = catalog.quantitySet(release.id, name_)
function member(setName_: TemplateSetName, path_: TemplateMemberPath): ifc.TemplateMemberReference =
  catalog.member(release.id, setName_, path_)
function memberByName(setName_: String, path_: String): ifc.TemplateMemberReference =
  catalog.member(release.id, setName_, path_)
function property(setName_: PropertySetName, path_: TemplateMemberPath): ifc.TemplateMemberReference =
  catalog.property(release.id, setName_, path_)
function propertyByName(setName_: String, path_: String): ifc.TemplateMemberReference =
  catalog.property(release.id, setName_, path_)
function quantity(setName_: QuantitySetName, path_: TemplateMemberPath): ifc.TemplateMemberReference =
  catalog.quantity(release.id, setName_, path_)
function quantityByName(setName_: String, path_: String): ifc.TemplateMemberReference =
  catalog.quantity(release.id, setName_, path_)
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-dir", required=True, type=Path)
    parser.add_argument("--output-dir", required=True, type=Path)
    parser.add_argument("--package-version", required=True)
    args = parser.parse_args()
    if args.package_version != "0.3.0":
        raise SystemExit("template catalog renderer is pinned to package version 0.3.0")
    loaded = [read_edition(args.source_dir / edition.file_name, edition) for edition in EDITIONS]
    catalogs = [item[0] for item in loaded]
    provenance = [item[1] for item in loaded]
    deltas = [catalogs[0]]
    removed: list[list[str]] = [[]]
    added: list[list[str]] = [[]]
    changed: list[list[str]] = [[]]
    for previous, current in zip(catalogs[:-1], catalogs[1:], strict=True):
        deltas.append({name: value for name, value in current.items() if previous.get(name) != value})
        removed.append(sorted(set(previous) - set(current)))
        added.append(sorted(set(current) - set(previous)))
        changed.append(sorted(name for name in set(previous) & set(current) if previous[name] != current[name]))

    all_names = sorted(set().union(*(set(catalog) for catalog in catalogs)))
    property_names = sorted(name for name in all_names if any(catalog.get(name) and catalog[name].kind == "psd" for catalog in catalogs))
    quantity_names = sorted(name for name in all_names if any(catalog.get(name) and catalog[name].kind == "qto" for catalog in catalogs))
    member_paths = sorted({path for catalog in catalogs for value in catalog.values() for path, _ in value.members})
    names_body = "\n".join((
        render_union("TemplateSetName", all_names),
        render_union("PropertySetName", property_names),
        render_union("QuantitySetName", quantity_names),
        render_union("TemplateMemberPath", member_paths),
        f"templateSetNames: List<TemplateSetName> = {pkl_list(all_names)}",
        f"propertySetNames: List<PropertySetName> = {pkl_list(property_names)}",
        f"quantitySetNames: List<QuantitySetName> = {pkl_list(quantity_names)}",
        f"templateMemberPaths: List<TemplateMemberPath> = {pkl_list(member_paths)}\n",
    ))
    write(args.output_dir / "internal/TemplateNames.pkl", module("TemplateNames", names_body))

    module_names = ("TemplateIfc2x3Data", "TemplateIfc4Data", "TemplateIfc4x3Data")
    aliases = ("ifc2x3", "ifc4", "ifc4x3")
    for index, (module_name, alias) in enumerate(zip(module_names, aliases, strict=True)):
        definition_name = "definitions" if index == 0 else "delta"
        body = render_definitions(definition_name, deltas[index])
        if index:
            body += f"removed: List<String> = {pkl_list(removed[index])}\n"
        body += render_provenance("sources", provenance[index])
        write(args.output_dir / f"internal/{module_name}.pkl", module(module_name, body, 'import "../ifc.pkl" as ifc'))

    transitions_body = "\n".join((
        f"ifc4Added: List<String> = {pkl_list(added[1])}",
        f"ifc4Removed: List<String> = {pkl_list(removed[1])}",
        f"ifc4Changed: List<String> = {pkl_list(changed[1])}",
        f"ifc4x3Added: List<String> = {pkl_list(added[2])}",
        f"ifc4x3Removed: List<String> = {pkl_list(removed[2])}",
        f"ifc4x3Changed: List<String> = {pkl_list(changed[2])}\n",
    ))
    write(args.output_dir / "internal/TemplateTransitions.pkl", module("TemplateTransitions", transitions_body))
    write(args.output_dir / "TemplateCatalog.pkl", render_facade(
        catalogs, provenance, deltas, removed, added, changed, args.package_version,
    ))
    template_views = args.output_dir / "templates"
    template_views.mkdir(parents=True, exist_ok=True)
    for edition in EDITIONS:
        write(template_views / f"{edition.module_name}.pkl", render_version_view(edition))
    print(
        f"wrote template catalog: sets={len(all_names)} members={sum(len(v.members) for v in catalogs[-1].values())} "
        f"deltas={len(deltas[0])}/{len(deltas[1])}/{len(deltas[2])}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
